source 'https://github.com/CocoaPods/Specs.git'

target 'ALDTimer', :exclusive => true do
  pod "ALDTimer", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "ALDTimer", :path => "../"

  
end
